---
title: "Conferences to consider"
---


***

## [ENAR](https://www.enar.org/meetings/spring2020/index.cfm)

[Fostering Diversity in Biostatistics Workshop](https://enar.org/meetings/FosteringDiversity/) 

***

## American Statistical Association (ASA) Conferences



For travel to any ASA conference, including:

* [Joint Statistical Meetings](https://www.amstat.org/meetings/joint-statistical-meetings) 

	+ With nearly 7,000 attendees, JSM is the largest gathering of statisticians and data scientists in North America.
		
* [Conference on Statistical Practice](https://www.amstat.org/meetings/conference-on-statistical-practice) 

	+  CSP brings together hundreds of statistical practitioners—including data analysts, researchers, and scientists—engaged in the application of statistics on a daily basis.
	
* [Symposium on Data Science & Statistics](https://www.amstat.org/meetings/symposium-on-data-science-amp-statistics)

  + SDSS provides a unique opportunity for data scientists, computer scientists, and statisticians to come together and exchange ideas.
		
* [Women in Statistics and Data Science Conference](https://www.amstat.org/meetings/women-in-statistics-and-data-science) 

	+ WSDS is tailored for women in the fields of statistics and data science. It is geared toward women at all career levels in academia, business, industry, and government
		
* [International Conference on Health Policy Statistics](https://www.amstat.org/meetings/international-conference-on-health-policy-statistics) 

	+ (ICHPS), organized by the Health Policy Statistics Section of the ASA, has played a vital role in the dissemination process of health policy (and health services) statistics. ICHPS provides a unique forum for discussing research needs and solutions to the methodological challenges in the design of studies and analysis of data for health policy research.

### [ASA Student Travel Fund](https://www.amstat.org/ASA/Your-Career/Awards/Student-and-Early-Career-Travel-Fund.aspx)

**To be eligible, applicants must:**

* Be enrolled in an undergraduate or graduate program in statistics or data science
* Be a Student or Early Career member of the ASA in good standing at the time of application
* Apply at least three months prior to the start of the ASA conference for which the applicant is applying for support. 

Winners will be announced no longer than two months prior to the conference start date.


### [ASA Student Paper Competitions for JSM](https://www.amstat.org/ASA/Your-Career/Student-Paper-Competitions.aspx)

The winners of best paper competitions earn travel awards to JSM. The following general policies and procedures apply to all ASA section competitions (see individual sections at the link for further applicable instructions):

* Sections must receive all materials by December 15. *Some sections have earlier deadlines, so check each section’s website for dates.*
* Students planning to participate in section competitions must adhere to the eligibility, paper format, submission process, and other requirements of the sections to which they are applying.


Winners will be notified by January 15.

		
***
