---
title: "Brittney E. Bailey"
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)

library(tidyverse)
library(fontawesome)
library(emojifont)
library(kableExtra)
library(rvest)
# google fonts
#https://fonts.google.com/

#customizing
#https://rstudio4edu.github.io/rstudio4edu-book/doc-fancy.html
```


I am currently an [Assistant Professor of Statistics at Amherst College](https://www.amherst.edu/people/facstaff/bebailey). I graduated with a BA in Mathematics from Messiah College, then completed my PhD in Biostatistics at The Ohio State University in 2018. My research explores statistical methods for dealing with missing data and multilevel data, and her collaborations have focused on ways to improve mental health and wellbeing. 

As a first-generation scholar, a person who was raised in poverty, and a Black woman in STEM, I am dedicated to supporting students with similar experiences and works to create environments where all students can thrive. To this end, I co-developed the [STEM Incubator Program](https://www.amherst.edu/news/news_releases/2020/10-2020/the-incubator-program-hatching-the-stem-scientists-of-the-future) at Amherst College and serve as Vice Chair of the American Statistical Association's [Committee on Minorities in Statistics](https://community.amstat.org/cmis/home), as well as a Co-Chair of the [StatFest](https://community.amstat.org/cmis/events/statfest) 2024 Planning Committee. 

