---
title: "Research"
output: html_document
bibliography: "bib/authored-works.bib"
csl: "bib/american-statistical-association.csl"
nocite: '@*'
---

## Summary

MY THEORETICAL WORK focuses on tackling the inevitable people problems of **nested clinical trials**,  where participants are members of intact groups (*e.g., communities, workplaces, schools*) or placed into groups during the study (*e.g., therapy groups, training classes*). How do we appropriately **account for the correlation within groups** when we analyze data from these designs, and how do we **handle missing data** in these scenarios? I demonstrated the strength of a logistic mixed effects model for binary outcome data from partially nested designs, and developed a predictive mean matching approach for multiple imputation of missing continuous data in cluster randomized trials. 

IN PRACTICE, I am interested in understanding the **effects of stress on health** and psychological well-being, and working with experts to **develop broadly accessible interventions** to mitigate the effect of stress on health. To this end, I spent several years as a collaborating biostatistician in the [Stress and Health Lab](http://pni.osumc.edu/stressandhealth/research.htm) of the [Institute for Behavioral Medicine Research](https://wexnermedical.osu.edu/neurological-institute/departments-and-centers/research-centers/institute-for-behavioral-medicine-research), training directly with [Dr. Janice Kiecolt-Glaser](https://wexnermedical.osu.edu/neurological-institute/researchers/janice-kiecolt-glaser-phd), a leader in the field of **psychoneuroimmunology**.  In the realm of cognitive psychology, I am currently working with [Dr. Sarah Bunnell](http://www.beinghumaninstem.com/dr-bunnell-profile.html) and Amherst College students to investigate meaning-making in public narrative of childhood sexual abuse.. 


## Publications